# Example Pipeline Configuration
# This file defines a sequence of processing steps to run on MGEF records

name: "MGEF Processing Pipeline"
description: "Process MGEF records through multiple steps"
input_file: "../data/Export_MGEF.json"
file_base: "MGEF_Analysis"  # Base name for all output files
overwrite: true  # Allow overwriting of existing output files

steps:
  - type: "select-winners"
    description: "Select winning records using default criteria (winning: true)"
    step_index: 1  # Will create Step-1.MGEF_Analysis.json

  - type: "trim"
    description: "Trim records using logic profile"
    step_index: 2  # Will create Step-2.MGEF_Analysis.json
    args:
      record_type: "MGEF"
      profile: "logic"
      remove_nulls: true

  - type: "cleanup"
    description: "Remove processor metadata from final output"
    step_index: 3  # Will create Step-3.MGEF_Analysis.json


