# Import base pipeline configuration
name: 'MGEF Analysis Pipeline'
description: 'Process MGEF data for analysis'
input: 'config/scroll-craft-pre/mgef/decode.json'
output: '../scroll-crafting/primaries/mgef.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Remove MGEF Specific Fields'
    type: 'remove-fields'
    description: 'Remove MGEF-specific fields that are not needed for analysis'
    fields:
      header: 'all'
      record: 'all'

  - from: 'local'
    name: 'Remove MGEF Data Fields'
    type: 'remove-fields'
    description: 'Remove specific MGEF data fields to clean up the dataset'
    remove_fields:
      - 'decodedData.SNDD'
      - 'decodedData.DATA.unknown1'
      - 'decodedData.DATA.castingLight'
      - 'decodedData.DATA.taperWeight'
      - 'decodedData.DATA.hitShader'
      - 'decodedData.DATA.enchantShader'
      - 'decodedData.DATA.area'
      - 'decodedData.DATA.castingTime'
      - 'decodedData.DATA.taperCurve'
      - 'decodedData.DATA.taperDuration'
      - 'decodedData.DATA.secondAVWeight'
      # - 'decodedData.DATA.effectType'
      - 'decodedData.DATA.projectileID'
      - 'decodedData.DATA.explosionID'
      - 'decodedData.DATA.castType'
      - 'decodedData.DATA.deliveryType'
      # - 'decodedData.DATA.secondAV'
      - 'decodedData.DATA.castingArt'
      - 'decodedData.DATA.hitEffectArt'
      - 'decodedData.DATA.impactDataID'
      - 'decodedData.DATA.skillUsageMult'
      - 'decodedData.DATA.dualCastID'
      - 'decodedData.DATA.dualCastScale'
      - 'decodedData.DATA.enchantArtID'
      - 'decodedData.DATA.nullData1'
      - 'decodedData.DATA.nullData2'
      - 'decodedData.DATA.equipAbility'
      - 'decodedData.DATA.imageSpaceModID'
      - 'decodedData.DATA.soundVolume'
      - 'decodedData.DATA.scriptAIDataScore'
      - 'decodedData.DATA.scriptAIDataDelayTime'

  - from: 'local'
    name: 'Rename decodedData to MGEF'
    type: 'rename-fields'
    description: 'Rename decodedData field to MGEF for scroll crafting primaries'
    mappings:
      decodedData: 'data'
