# Import base pipeline configuration
name: 'MESG Analysis Pipeline'
description: 'Process MESG data for analysis'
input: '../output/skyrim-extractor/lorerim/MESG.json'
output: '../output/parsing-pipeline/lorerim/mesg-analysis.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Filter Winner Records'
    type: 'filter-records'
    description: 'Filter to only include records where isWinner is true'
    criteria:
      - field: 'meta.isWinner'
        operator: 'equals'
        value: true

  - from: 'local'
    name: 'Decode Binary Records'
    type: 'buffer-decoder'
    description: 'Decode binary record data into structured format'
    recordType: 'MESG'
    loadPluginMetadata: true
    pluginMetadataPath: '../output/skyrim-extractor/lorerim/plugin-metadata-map.json'
    multithreaded: true
    maxWorkers: 4

  - from: 'local'
    name: 'Remove MESG Specific Fields'
    type: 'remove-fields'
    description: 'Remove MESG-specific fields that are not needed for analysis'
    fields:
      header: 'all'
      record: 'all' 