# Import base pipeline configuration
name: "QUST Analysis Pipeline"
description: "Process QUST data for analysis"
input: "../output/skyrim-extractor/lorerim/QUST.json"
output: "../pipeline-projects/religion/wintersun-qust.json"

# Use stages from base template
stages:
  - from: "local"
    name: "Filter QUST Records"
    type: "filter-records"
    description: "Filter to only include records from Wintersun plugin"
    criteria:
      - field: "meta.formId"
        operator: "equals"
        value: "0x04005901"

  - from: "local"
    name: "Filter Winner Records"
    type: "filter-records"
    description: "Filter to only include records where isWinner is true"
    criteria:
      - field: "meta.isWinner"
        operator: "equals"
        value: true

  - from: "local"
    name: "Filter QUST Records"
    type: "filter-records"
    description: "Filter to only include records from Wintersun plugin"
    criteria:
      - field: "meta.plugin"
        operator: "contains"
        value: "Wintersun"

  - from: "local"
    name: "Decode Binary Records"
    type: "buffer-decoder"
    description: "Decode binary record data into structured format"
    recordType: "QUST"
    loadPluginMetadata: true
    pluginMetadataPath: "../output/skyrim-extractor/lorerim/plugin-metadata-map.json"
    # multithreaded: true
    # maxWorkers: 4

  - from: "local"
    name: "Extract VMAD Properties"
    type: "extract-field"
    description: "Extract properties from VMAD scripts and make them top-level documents"
    field: "decodedData.VMAD.scripts[0].properties"

  - from: "local"
    name: "Filter Wintersun Records"
    type: "filter-records"
    description: "Filter to only include records from Wintersun plugin"
    criteria:
      - field: "propertyName"
        operator: "in-list"
        value:
          [
            "WSN_DeityName",
            "WSN_DeityDescription",
            "WSN_DeityIcon",
            "WSN_DeityEffect",
            "WSN_DeityEffectDescription",
            "WSN_DeityEffectIcon",
            "WSN_Blessing",
            "WSN_Boon1",
            "WSN_Boon2",
            "WSN_Tenet",
            "WSN_DivineType",
            "WSN_FavoredRace0",
            "WSN_FavoredRace1",
          ]
