# Import base pipeline configuration
name: "QUST Analysis Pipeline"
description: "Process QUST data for analysis"
input: "../output/skyrim-extractor/lorerim/QUST.json"
output: "../pipeline-projects/religion/wintersun-qust.json"

# Use stages from base template
stages:
  - from: "local"
    name: "Filter QUST Records"
    type: "filter-records"
    description: "Filter to only include records from Wintersun plugin"
    criteria:
      - field: "meta.formId"
        operator: "equals"
        value: "0x04005901"

  - from: "local"
    name: "Filter Winner Records"
    type: "filter-records"
    description: "Filter to only include records where isWinner is true"
    criteria:
      - field: "meta.isWinner"
        operator: "equals"
        value: true

  - from: "local"
    name: "Filter QUST Records"
    type: "filter-records"
    description: "Filter to only include records from Wintersun plugin"
    criteria:
      - field: "meta.plugin"
        operator: "contains"
        value: "Wintersun"

  - from: "local"
    name: "Decode Binary Records"
    type: "buffer-decoder"
    description: "Decode binary record data into structured format"
    recordType: "QUST"
    loadPluginMetadata: true
    pluginMetadataPath: "../output/skyrim-extractor/lorerim/plugin-metadata-map.json"
    # multithreaded: true
    # maxWorkers: 4

  - from: "local"
    name: "Extract VMAD Properties"
    type: "extract-field"
    description: "Extract properties from VMAD scripts and make them siblings of decodedData"
    field: "decodedData.VMAD.scripts[0].properties"
    outputMode: "sibling"
    preserveSource: false

  - from: "local"
    name: "Remove Technical Fields"
    type: "remove-fields"
    description: "Remove decodedData, header, and record fields to clean up the output"
    fields:
      decodedData: "all"
      header: "all"
      record: "all"

  - from: "local"
    name: "Filter Wintersun Records"
    type: "filter-records"
    description: "Filter to only include records from Wintersun plugin"
    criteria:
      - field: "properties.propertyName"
        operator: "in-list"
        value:
          [
            "WSN_DeityName",
            "WSN_Blessing",
            "WSN_Boon1",
            "WSN_Boon2",
            "WSN_Tenet",
            "WSN_DivineType",
            "WSN_FavoredRace0",
            "WSN_FavoredRace1",
          ]

  - from: "local"
    name: "Remove Unused Fields"
    type: "remove-fields"
    description: "Remove unused fields to clean up the data structure"
    remove_fields:
      - "meta.formId"
      - "meta.globalFormId"
      - "meta.stackOrder"
      - "meta.isWinner"
      - "properties.propertyType"
      - "properties.propertyStatus"

  - from: "local"
    name: "Rename Properties Field"
    type: "rename-fields"
    description: "Rename properties field to wsnList for better clarity"
    mappings:
      properties.propertyName: "name"
      properties.propertyValue: "values"
      properties: "religionData"

  - from: "local"
    name: "Resolve FormIDs"
    type: "formid-resolver"
    description: "Resolve local FormIDs to global FormIDs in religion data"
    pluginRegistryPath: "../output/skyrim-extractor/lorerim/plugin-metadata-map.json"
    contextPluginField: "meta.plugin"
    targetFields:
      - field: "religionData.values[].formId"
        outputField: "religionData.values[].formIdResolved"
    conditions:
      - field: "meta.plugin"
        operator: "contains"
        value: "Wintersun"

  - from: "local"
    name: "Remove Unused Fields"
    type: "remove-fields"
    description: "Remove unused fields to clean up the data structure"
    remove_fields:
      - "religionData.values[].formId"
      - "religionData.values[].alias"

  - from: "local"
    name: "Pluck FormID Resolved"
    type: "pluck-array-values"
    description: "Replace objects in religionData.values with their formId_resolved value, but only if they have that field."
    arrayField: "religionData.values"
    targetField: "formId_resolved"
