name: 'AVIF-PERK Merge Pipeline'
description: 'Merges AVIF records with related PERK records, replacing PNAM references with actual PERK data'
input: 'output/avif-analysis.json'
output: 'output/avif-perk-merged.json'
stages:
  - name: 'Merge AVIF with PERK Records'
    type: 'merge-records'
    description: 'Replace PNAM references in AVIF records with actual PERK record data'
    sourceFile: 'output/perk-analysis.json'
    sourceRecordType: 'PERK'
    mappings:
      - sourceField: 'meta.formId'
        targetField: 'decodedData.perkSections[].PNAM'
        matchType: 'exact'
    mergeField: 'relatedPerks'
    mergeStrategy: 'first'
    overwriteReference: true
