# Import base pipeline configuration
name: 'MGEF Analysis Pipeline'
description: 'Process MGEF data for analysis'
# input: '../output/skyrim-extractor/mod-samples/MGEF.json'
input: '../output/parsing-pipeline/1.MGEF_Analysis.json'
output: '../output/parsing-pipeline/1.MGEF_Analysis.json'

# Use stages from base template
stages:
  # - from: 'local'
  #   name: 'Decode Binary Records'
  #   type: 'buffer-decoder'
  #   description: 'Decode binary record data into structured format'
  #   recordType: 'MGEF'

  - from: 'local'
    name: 'Remove MGEF Specific Fields'
    type: 'remove-fields'
    description: 'Remove MGEF-specific fields that are not needed for analysis'
    fields:
      data: 'all'
      header: 'all'
      decodedData:
        - DATA:
            - effectShader
            - enchantShader
            - castingSound
            - boltSound
            - hitSound
            - areaSound
            - boltSoundLoop
            - hitShader
            - castingArt
            - boltArt
            - hitArt
            - enchantArt
            - enchantSound
            - impactDataSet
