# Import base pipeline configuration
name: 'AVIF Analysis Pipeline'
description: 'Process AVIF data for analysis'
input: '../output/skyrim-extractor/lorerim/AVIF.json'
output: '../output/parsing-pipeline/lorerim/avif-analysis.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Select Winners'
    type: 'filter-records'
    description: 'Select records that are winners'
    criteria:
      - field: 'meta.isWinner'
        operator: 'equals'
        value: true

  - from: 'local'
    name: 'Decode Binary Records'
    type: 'buffer-decoder'
    description: 'Decode binary record data into structured format'
    recordType: 'AVIF'

  - from: 'local'
    name: 'Remove AVIF Specific Fields'
    type: 'remove-fields'
    description: 'Remove AVIF-specific fields that are not needed for analysis'
    fields:
      record: 'all'
      header: 'all'
      # meta: 'all'
      decodedData:
        - 'perkSections'

  # - from: 'local'
  #   name: 'Flatten Decoded Data'
  #   type: 'flatten-fields'
  #   description: 'Flatten decodedData into the top-level record for easier analysis'
  #   fields:
  #     - 'decodedData'

  - from: 'local'
    name: 'Filter Skill EDIDs'
    type: 'filter-records'
    description: 'Only include records with EDIDs matching PlayerSkillEdid enum values'
    criteria:
      - field: 'decodedData.EDID'
        operator: 'in-list'
        value:
          - 'AVOneHanded'
          - 'AVTwoHanded'
          - 'AVMarksman'
          - 'AVBlock'
          - 'AVHeavyArmor'
          - 'AVLightArmor'
          - 'AVPickpocket'
          - 'AVLockpicking'
          - 'AVSneak'
          - 'AVSmithing'
          - 'AVAlchemy'
          - 'AVEnchanting'
          - 'AVAlteration'
          - 'AVConjuration'
          - 'AVDestruction'
          - 'AVMysticism'
          - 'AVRestoration'
          - 'AVSpeechcraft'
