# Import base pipeline configuration
name: 'FLST Analysis Pipeline'
description: 'Process FLST data for analysis'
input: '../output/skyrim-extractor/lorerim/FLST.json'
# output: '../output/parsing-pipeline/lorerim/flst-analysis.json'
output: '../scroll-crafting/primaries/flst.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Filter FLST Records'
    type: 'filter-records'
    description: 'Filter to only include records where isWinner is true'
    criteria:
      - field: 'meta.isWinner'
        operator: 'equals'
        value: true

  - from: 'local'
    name: 'Decode Binary Records'
    type: 'buffer-decoder'
    description: 'Decode binary record data into structured format'
    recordType: 'FLST'
    loadPluginMetadata: true
    pluginMetadataPath: '../output/skyrim-extractor/lorerim/plugin-metadata-map.json'
    multithreaded: true
    maxWorkers: 4

  - from: 'local'
    name: 'Remove FLST Specific Fields'
    type: 'remove-fields'
    description: 'Remove FLST-specific fields that are not needed for analysis'
    fields:
      header: 'all'
      record: 'all'

  - from: 'local'
    name: 'Flatten Meta and Decoded Data'
    type: 'flatten-fields'
    description: 'Flatten meta and decoded data fields to simplify the record structure'
    fields:
      - 'meta'
      - 'decodedData'
