# Import base pipeline configuration
name: 'MGEF Analysis Pipeline'
description: 'Process MGEF data for analysis'
input: '../output/parsing-pipeline/lorerim/mgef-analysis.json'
output: '../output/parsing-pipeline/lorerim/mgef-analysis-pt2.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Remove MGEF Specific Fields'
    type: 'remove-fields'
    description: 'Remove MGEF-specific fields that are not needed for analysis'
    fields:
      data: 'all'
      header: 'all'
      record: 'all'

  - from: 'local'
    name: 'Remove MGEF Data Fields'
    type: 'remove-fields'
    description: 'Remove specific MGEF data fields to clean up the dataset'
    fields:
      decodedData:
        DATA:
          # - 'baseCost'
          # - 'relatedID'
          # - 'skill'
          # - 'resistanceAV'
          - 'unknown1'
          - 'castingLight'
          - 'taperWeight'
          - 'hitShader'
          - 'enchantShader'
          # - 'skillLevel'
          - 'area'
          - 'castingTime'
          - 'taperCurve'
          - 'taperDuration'
          - 'secondAVWeight'
          - 'effectType'
          # - 'primaryAV'
          - 'projectileID'
          - 'explosionID'
          - 'castType'
          - 'deliveryType'
          - 'secondAV'
          - 'castingArt'
          - 'hitEffectArt'
          - 'impactDataID'
          - 'skillUsageMult'
          - 'dualCastID'
          - 'dualCastScale'
          - 'enchantArtID'
          - 'nullData1'
          - 'nullData2'
          - 'equipAbility'
          - 'imageSpaceModID'
          # - 'perkID'
          - 'soundVolume'
          - 'scriptAIDataScore'
          - 'scriptAIDataDelayTime'
