# Import base pipeline configuration
name: 'PERK Analysis Pipeline'
description: 'Process PERK data for analysis'
input: '../output/skyrim-extractor/lorerim/PERK.json'
output: '../output/parsing-pipeline/lorerim/perk-analysis.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Filter Winner Records'
    type: 'filter-records'
    description: 'Filter to only include records where isWinner is true'
    criteria:
      - field: 'meta.isWinner'
        operator: 'equals'
        value: true

  - name: 'Multithreaded PERK Decoder'
    type: 'buffer-decoder'
    description: 'Decode PERK records using multiple worker threads for improved performance'
    recordType: 'PERK'
    multithreaded: true
    maxWorkers: 4 # Optional: limit to 4 workers
    loadPluginMetadata: true
    enabled: true
    pluginMetadataPath: '../output/skyrim-extractor/lorerim/plugin-metadata-map.json'

  - from: 'local'
    name: 'Remove PERK Specific Fields'
    type: 'remove-fields'
    description: 'Remove PERK-specific fields that are not needed for analysis'
    fields:
      record: 'all'
      header: 'all'
      # meta: 'all'

  # - from: 'local'
  #   name: 'Flatten Decoded Data'
  #   type: 'flatten-fields'
  #   description: 'Flatten decodedData into the top-level record for easier analysis'
  #   fields:
  #     - 'decodedData'
