# AVIF to PERK Merge Pipeline
name: 'AVIF-PERK Merge Pipeline'
description: 'Merge AVIF records with their related PERK records'
input: '../output/parsing-pipeline/lorerim/avif-analysis.json'
output: '../output/parsing-pipeline/lorerim/processed/player-perk-docs-pre.json'

stages:
  - name: 'Remove Processing Fields'
    type: 'remove-fields'
    description: 'Remove fields that were only needed for processing'
    fields:
      record: 'all'
      header: 'all'
      meta: 'all'

  - name: 'Flatten decodedData Fields'
    type: 'flatten-fields'
    description: 'Flatten the decodedData field to make nested data more accessible'
    fields: ['decodedData']

  # Merge PERK Records
  - from: 'local'
    name: 'Merge PERK Records'
    type: 'merge-records'
    description: 'Merge PERK records that are referenced by AVIF perkSections'
    sourceFile: '../output/parsing-pipeline/lorerim/perk-analysis.json'
    sourceRecordType: 'PERK'
    mappings:
      - sourceField: 'perk-mapping'
        targetField: 'perkSections[].PNAM'
        matchField: 'meta.globalFormId'
        dataField: 'decodedData'
        matchType: 'exact'
    mergeField: 'PERK'
    mergeStrategy: 'first'

  - name: 'Remove Noise Fields'
    type: 'remove-fields'
    description: 'Remove technical noise fields while keeping essential documentation data'
    remove_fields:
      # TRIM AVIF Values
      - 'AVSK'

      # Trim AVIF perkSection Values
      - 'perkSections[].SNAM'
      - 'perkSections[].FNAM'
      - 'perkSections[].HNAM'
      - 'perkSections[].VNAM'
      - 'perkSections[].PNAM'
      - 'perkSections[].DATA'
      - 'perkSections[].PRKE'
      - 'perkSections[].PRKC'
      - 'perkSections[].EPFT'
      - 'perkSections[].PRKH'

      # Trim Perk Records - Direct fields
      - 'perkSections[].PERK.CTDA[].unknown'
      - 'perkSections[].PERK.CTDA[].unknown2'
      - 'perkSections[].PERK.CTDA[].unknown3'
      - 'perkSections[].PERK.CTDA[].padding'
      - 'perkSections[].PERK.CTDA[].padding2'
      - 'perkSections[].PERK.CTDA[].param1'
      - 'perkSections[].PERK.CTDA[].param2'
      - 'perkSections[].PERK.CTDA[].unknown4'
      - 'perkSections[].PERK.CTDA[].operator.rawOperator'
      - 'perkSections[].PERK.CTDA[].operator.rawCompareOperator'
      - 'perkSections[].PERK.CTDA[].operator.rawFlags'

      # Trim Perk Records - Nested sections
      - 'perkSections[].PERK.sections[].CTDA[].unknown'
      - 'perkSections[].PERK.sections[].CTDA[].unknown2'
      - 'perkSections[].PERK.sections[].CTDA[].unknown3'
      - 'perkSections[].PERK.sections[].CTDA[].padding'
      - 'perkSections[].PERK.sections[].CTDA[].padding2'
      - 'perkSections[].PERK.sections[].CTDA[].param1'
      - 'perkSections[].PERK.sections[].CTDA[].param2'
      - 'perkSections[].PERK.sections[].CTDA[].unknown4'
      - 'perkSections[].PERK.sections[].CTDA[].operator.rawOperator'
      - 'perkSections[].PERK.sections[].CTDA[].operator.rawCompareOperator'
      - 'perkSections[].PERK.sections[].CTDA[].operator.rawFlags'
      - 'perkSections[].PERK.sections[].CTDA[].reference'
      - 'perkSections[].PERK.sections[].CTDA[].comparisonValue'
      - 'perkSections[].PERK.sections[].PRKF'
      - 'perkSections[].PERK.sections[].EPFD'
      - 'perkSections[].PERK.sections[].DATA.padding'
      - 'perkSections[].PERK.sections[].DATA.padding2'
      - 'perkSections[].PERK.sections[].DATA.padding3'
