# Import base pipeline configuration
name: 'QUST Analysis Pipeline'
description: 'Process QUST data for analysis'
input: '../output/skyrim-extractor/lorerim/QUST.json'
output: '../output/parsing-pipeline/lorerim/qust-analysis.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Filter QUST Records'
    type: 'filter-records'
    description: 'Filter to only include records from Wintersun plugin'
    criteria:
      - field: 'meta.formId'
        operator: 'equals'
        value: '0x04005901'

  - from: 'local'
    name: 'Filter Winner Records'
    type: 'filter-records'
    description: 'Filter to only include records where isWinner is true'
    criteria:
      - field: 'meta.isWinner'
        operator: 'equals'
        value: true

  - from: 'local'
    name: 'Filter QUST Records'
    type: 'filter-records'
    description: 'Filter to only include records from Wintersun plugin'
    criteria:
      - field: 'meta.plugin'
        operator: 'contains'
        value: 'Wintersun'

  # - from: 'local'
  #   name: 'Sample Records'
  #   type: 'sample-records'
  #   description: 'Get 3 sample records for analysis'
  #   sampleSize: 3
  #   randomSeed: 42
  - from: 'local'
    name: 'Decode Binary Records'
    type: 'buffer-decoder'
    description: 'Decode binary record data into structured format'
    recordType: 'QUST'
    loadPluginMetadata: true
    pluginMetadataPath: '../output/skyrim-extractor/lorerim/plugin-metadata-map.json'
    # multithreaded: true
    # maxWorkers: 4

  - from: 'local'
    name: 'Remove QUST Specific Fields'
    type: 'remove-fields'
    description: 'Remove QUST-specific fields that are not needed for analysis'
    fields:
      header: 'all'
      # record: 'all'
