# Import base pipeline configuration
name: 'Spel Analysis Pipeline'
description: 'Process Spel data for analysis'
input: '../output/parsing-pipeline/lorerim/spel-analysis.json'
output: '../output/parsing-pipeline/lorerim/spel-analysis-pt2.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Filter Wintersun Records'
    type: 'filter-records'
    description: 'Filter to only include records from Wintersun plugins'
    criteria:
      - field: 'meta.plugin'
        operator: 'contains'
        value: 'Wintersun'

  - from: 'local'
    name: 'Remove Spel Specific Fields'
    type: 'remove-fields'
    description: 'Remove Spel-specific fields that are not needed for analysis'
    fields:
      data: 'all'
      header: 'all'
      record: 'all'
