# Import base pipeline configuration
name: 'SPEL Analysis Pipeline'
description: 'Process SPEL data for analysis'
input: '../output/skyrim-extractor/lorerim/SPEL.json'
output: '../output/parsing-pipeline/lorerim/spel-analysis.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Decode Binary Records'
    type: 'buffer-decoder'
    description: 'Decode binary record data into structured format'
    recordType: 'SPEL'
    loadPluginMetadata: true
    pluginMetadataPath: '../output/skyrim-extractor/lorerim/plugin-metadata-map.json'
    multithreaded: true
    maxWorkers: 4

  - from: 'local'
    name: 'Remove SPEL Specific Fields'
    type: 'remove-fields'
    description: 'Remove SPEL-specific fields that are not needed for analysis'
    fields:
      record: 'all'
      header: 'all'
