# Import base pipeline configuration
name: 'FLST Analysis Pipeline'
description: 'Process FLST data for analysis'
input: 'config/scroll-craft-pre/flst/decode.json'
output: '../scroll-crafting/primaries/flst.json'

# Use stages from base template
stages:
  - from: 'local'
    name: 'Remove FLST Specific Fields'
    type: 'remove-fields'
    description: 'Remove FLST-specific fields that are not needed for analysis'
    fields:
      header: 'all'
      record: 'all'

  - from: 'local'
    name: 'Rename decodedData to FLST'
    type: 'rename-fields'
    description: 'Rename decodedData field to FLST for scroll crafting primaries'
    mappings:
      decodedData: 'data'

